apiVersion: v1
kind: PersistentVolume
metadata:
  name: datamanage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data  # Путь на хосте для хранения данных
