apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamanagement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamanagement
  template:
    metadata:
      labels:
        app: datamanagement
    spec:
      containers:
      - name: datamanagement
        image: saturn0912/datamanagement:v1.1
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE
