apiVersion: v1
kind: Secret
metadata:
  name: db-secret  # Имя секрета, используемое для его идентификации
type: Opaque  # Тип секрета, который хранит произвольные данные в формате base64
data:
  MYSQL_HOST: MTkyLjE2OC4wLjEwOQ==  # Значение переменной окружения 'MYSQL_HOST' в формате base64 (значение: '192.168.0.109')
  MYSQL_USER: bWFuYWdlcl8wMA==    # Значение переменной окружения 'MYSQL_USER' в формате base64 (значение: 'manager_00')
  MYSQL_PASSWORD: TXlTdWgwOTEyIQ==  # Значение переменной окружения 'MYSQL_PASSWORD' в формате base64 (значение: 'MySuh0912!')
  MYSQL_DATABASE: cmVwYWlyX3JlcXVlc3Q=  # Значение переменной окружения 'MYSQL_DATABASE' в формате base64 (значение: 'repair_request')
