apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"  # Запуск каждые 5 минут
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob-container
            image: busybox
            command: ["sh", "-c", "echo Hello from Kubernetes CronJob! && sleep 30"]
          restartPolicy: OnFailure
