apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-job-container
        image: busybox
        command: ["sh", "-c", "echo Hello from Kubernetes Job! && sleep 30"]
      restartPolicy: OnFailure
