apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14-1
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluentd.conf
          subPath: fluentd.conf
        - name: log
          mountPath: /var/log/containers
        - name: pos
          mountPath: /fluentd/log/es-containers.log.pos
        env:
        - name: FLUENTD_SYSTEMD_CONF
          value: "disabled"
        - name: TZ
          value: Europe/Moscow  # Добавьте эту строку
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: log
        hostPath:
          path: /var/log/containers
      - name: pos
        hostPath:
          path: /fluentd/log/es-containers.log.pos
